### PR TITLE
DataHub Jupyter VM

### PR DESCRIPTION
**Pull request by enolfc**
New VM for integration of international providers that brings a Notebook deployment with a onedata client so users can get a browser based environment to test how the integration works.

### CODE REVIEW

**Comment by enolfc** [comment]
@gwarf @CatalinCondurache could you take a look?

**Comment by gwarf** [comment]
As it's apparently providing access over plain http, could some secrets be sent/displayed across this connection?

**Comment by enolfc** [comment]
> As it's apparently providing access over plain http, could some secrets be sent/displayed across this connection?

Any suggestion on how to make it https? We can create a host name in DynDNS and get a cert with Let's Encrypt, or maybe just use the default cert?

**Comment by andrea-manzi** [comment]
> > As it's apparently providing access over plain http, could some secrets be sent/displayed across this connection?
> 
> Any suggestion on how to make it https? We can create a host name in DynDNS and get a cert with Let's Encrypt, or maybe just use the default cert?

mmm things are getting complicated:-) what is the default cert you are referring to?

**Comment by gwarf** [comment]
The DynDNS + Let's Encrypt may be the nicest/cleaners solution, if it's doable and acceptable.
I guess it may also be possible to create a self signed cert and use it, it would trigger some warnings but still at least offer some encryption.
It's making things more complex, but if by default we offer an insecure VM that provides something fully working, we can be quite sure that some people will use it like this and it's not great...

**Comment by enolfc** [comment]
Now ready to use Let's Encrypt and with configuration explained already in docs.egi.eu

**Review by gwarf — APPROVED** [review]
LGTM!

**Pull request merged**
