### PR TITLE
3rd attempt: Convert supported Ubuntu templates from json to hcl #85 

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

See details and discussion in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/84

---

**Related issue :** https://github.com/EGI-Federation/fedcloud-vmi-templates/issues/72

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Any suggestions about this error?
https://github.com/EGI-Federation/fedcloud-vmi-templates/actions/runs/10525229402/job/29163585125?pr=87#step:8:46

**Comment by sebastian-luna-valero** [comment]
Not sure what's causing this error in the build workflow:

```bash
jq: error (at <stdin>:10): Cannot index string with string "id"
```

Produced by:

https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/e47134aae8acebfe0de1bdc16d9f8f4ed86c65c0/.github/workflows/build.yml#L66-L89

I just run the below locally and it works:

```bash
# configure access
export OIDC_AGENT_ACCOUNT=<my-account>
eval "$(fedcloud site env --site SCAI --vo vo.access.egi.eu)"
export OS_TOKEN=$(fedcloud openstack --site SCAI --vo vo.access.egi.eu token issue -c id -f value)

# deploy
DEPLOY_SITE="$(yq -r .clouds.deploy.site clouds.yaml)"
terraform apply -auto-approve -var-file="$DEPLOY_SITE.tfvars"
```

**Comment by enolfc** [comment]
Can you try to add some `set -x` in the `refresh.sh`? Not sure of what's going on, but it looks like something wrong in the credentials management

**Comment by sebastian-luna-valero** [comment]
One the other hand, currently I have pushed

```bash
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
 
     steps:
       - name: checkout code
@@ -23,11 +24,12 @@ jobs:
         with:
           matrix: true
           files: |
-             **/*.json
+             **/*.{json,hcl}

```

But I think it should be the below instead?


```bash
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
 
     steps:
       - name: checkout code
@@ -23,11 +24,12 @@ jobs:
         with:
           matrix: true
           files: |
-             **/*.json
+             **/*.hcl

```

What do you think?

**Review by enolfc — APPROVED** [review]
Let's go for it! Thanks!

**Pull request merged**
