### PR TITLE
Check the test actually works

### PR DESCRIPTION
**Pull request by enolfc**
This PR should fail tests
- Use non existent URL
- Break shasum

Not to merge, just making sure things work

### CODE REVIEW

**Comment by enolfc** [comment]
bummer 💥  the test is failing to find the updated files :)

**Comment by gwarf** [comment]
There is a fatal error, but not sure about the meaining: https://github.com/EGI-Federation/fedcloud-vmi-templates/runs/4854743821?check_suite_focus=true#step:4:18

And apparently the wrong chasum did pass

**Comment by enolfc** [comment]
> In this check that succeed there is a fatal error that is logged, but not sure about the meaning: https://github.com/EGI-Federation/fedcloud-vmi-templates/runs/4854743821?check_suite_focus=true#step:4:18

It seems the vars are not properly substituted
it should be
```git diff --name-only ${{ github.event.before }}..${{ github.event.after }}```

I think this before and after may not apply to pull requests, but to push

> 
> And apparently the wrong SHA sum did pass

It was not really tested

**Comment by enolfc** [comment]
And now it seems the SHA sum failed as expected.
I'm removing that one failure and see whether the wrong URL also fails

**Comment by enolfc** [comment]
And fails as expected:
```
Testing ubuntu/appdb/ubuntu-20.04.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: no-api.cloud.ifca.es
```

**Comment by enolfc** [comment]
Previous error:
```
SHA SUM does not match 839cb0896007854c07ebaf52849b1470f592ac3723d34825d0911fa757cea26e88c82bbace79164a306f241fba810dd7a89a0f09326ec8d02e50cc323341e9a4 83578089400785ec07ebaf52849b1470f592ac3723d34825d0911fa757cea26e88c82bbace79164a306f241fba810dd7a89a0f09326ec8d02e50cc323341e9a4!
```

**Comment by enolfc** [comment]
So getting back the working files. Now it can be merged

**Review by gwarf — APPROVED** [review]
Cool, that seem to be working great, congrats!

**Pull request merged**
