### PR TITLE
Regular Ubuntu 20.04 update

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Update to the image as it's expiring in 4 days

---

**Related issue :**

### CODE REVIEW

**Review by sebastian-luna-valero — APPROVED** [review]
Manual tests working for me, thanks!

**Comment by gwarf** [comment]
> > Manual tests working for me, thanks!
> 
> how can we automate this?

AKA @brucellino? 😇

**Comment by enolfc** [comment]
> > > Manual tests working for me, thanks!
> > 
> > 
> > how can we automate this?
> 
> AKA @brucellino? 😇

I guess we can:
1. upload the image to a site (which one?)
2. start the image with terraform
3. try to interact with the running VM - can we do this without a public IP? (this would be very helpful also for the argo probe)
4. destroy everything

**Comment by enolfc** [comment]
And if we do step 0, build the image as part of the action, then this would be 🚀

**Pull request merged**
