### PR TITLE
Compress resulting qcow2 image

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Compress resulting image to make things lighter

---

**Related issue :**

### CODE REVIEW

**Review by sebastian-luna-valero — APPROVED** [review]
Let's try it, looks good so far!

**Comment by enolfc** [comment]
> Let's try it, looks good so far!

Ideally the build should be done as part of the pull request but that would imply that anyone sending an PR could trigger the spawning of a VM and do something "wrong"

**Comment by sebastian-luna-valero** [comment]
I assumed forked repos don't get access to secrets (i.e. OIDC tokens) and therefore cannot trigger automatic builds from GitHub?

**Comment by enolfc** [comment]
Bummer, it failed and we have no logs of the failure and the VM is gone 😫

**Pull request merged**
