### PR TITLE
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by enolfc**
Reusing all stuff from 20.04

### CODE REVIEW

**Comment by gwarf** [comment]
🤔 
Screenshot 2022-05-05 at 17 12 36

**Comment by enolfc** [comment]
> 🤔 Screenshot 2022-05-05 at 17 12 36

Yes, I'm re-uploading. I started it once, Ctrl-C unintentionally, then repeated and I guess the command was not doing the right thing. So now I deleted it and it's on its way

**Comment by enolfc** [comment]
> > 🤔 Screenshot 2022-05-05 at 17 12 36
> 
> Yes, I'm re-uploading. I started it once, Ctrl-C unintentionally, then repeated and I guess the command was not doing the right thing. So now I deleted it and it's on its way

So I was redoing the upload and things kept failing... obviously I had forgot to fix the file name and was checking a non-existent file

**Review by gwarf — APPROVED** [review]
LGTM!
The tests you put in place are great :)

**Pull request merged**
